font-family = "Iosevka Term"
font-size = 21
theme = Oceanic Next
confirm-close-surface = false
title = " "
term = "xterm-256color"
macos-titlebar-proxy-icon = hidden
bell-features = no-title
window-width = 86
window-height = 21
